### ISSUE TITLE
v1.4.3

### ISSUE THREAD

**Issue by rp4k** [SlackingVeteran/frija#3]
windows version : 20H2

frija v1.4.3  

the log is putting out this error:

`09/11/2020 02:20:26
Error 102: Unable to find Firmware for SM-G975F/OXM
Please make sure all fields are correct or use Manual Mode

09/11/2020 02:21:16
Error reading config file: Object reference not set to an instance of an object.
Error reading config file: Object reference not set to an instance of an object.
Error reading config file: Object reference not set to an instance of an object.
Error 102: Unable to find Firmware for SM-G975F/OXM
Please make sure all fields are correct or use Manual Mode`

**Comment by SlackingVeteran** [comment]
Already replied on XDA
